# coding: utf-8

"""
    Ververica Platform API

    The Ververica Platform APIs, excluding Application Manager.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_api_tokens_response import ListApiTokensResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListApiTokensResponse(unittest.TestCase):
    """ListApiTokensResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListApiTokensResponse(self):
        """Test ListApiTokensResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_api_tokens_response.ListApiTokensResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
