# coding: utf-8

"""
    Ververica Platform API

    The Ververica Platform APIs, excluding Application Manager.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.delete_namespace_response import DeleteNamespaceResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteNamespaceResponse(unittest.TestCase):
    """DeleteNamespaceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteNamespaceResponse(self):
        """Test DeleteNamespaceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.delete_namespace_response.DeleteNamespaceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
