# coding: utf-8

"""
    Ververica Platform API

    The Ververica Platform APIs, excluding Application Manager.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiToken(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_time': 'datetime',
        'name': 'str',
        'role': 'str',
        'secret': 'str'
    }

    attribute_map = {
        'create_time': 'createTime',
        'name': 'name',
        'role': 'role',
        'secret': 'secret'
    }

    def __init__(self, create_time=None, name=None, role=None, secret=None):  # noqa: E501
        """ApiToken - a model defined in Swagger"""  # noqa: E501

        self._create_time = None
        self._name = None
        self._role = None
        self._secret = None
        self.discriminator = None

        if create_time is not None:
            self.create_time = create_time
        if name is not None:
            self.name = name
        if role is not None:
            self.role = role
        if secret is not None:
            self.secret = secret

    @property
    def create_time(self):
        """Gets the create_time of this ApiToken.  # noqa: E501


        :return: The create_time of this ApiToken.  # noqa: E501
        :rtype: datetime
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiToken.


        :param create_time: The create_time of this ApiToken.  # noqa: E501
        :type: datetime
        """

        self._create_time = create_time

    @property
    def name(self):
        """Gets the name of this ApiToken.  # noqa: E501


        :return: The name of this ApiToken.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiToken.


        :param name: The name of this ApiToken.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def role(self):
        """Gets the role of this ApiToken.  # noqa: E501


        :return: The role of this ApiToken.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ApiToken.


        :param role: The role of this ApiToken.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def secret(self):
        """Gets the secret of this ApiToken.  # noqa: E501


        :return: The secret of this ApiToken.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this ApiToken.


        :param secret: The secret of this ApiToken.  # noqa: E501
        :type: str
        """

        self._secret = secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiToken):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
